# Generated by Django 3.0.2 on 2020-01-16 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_profile_number_of_todos'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='number_of_todos',
            field=models.IntegerField(default=0),
        ),
    ]
